### ISSUE TITLE
Should we support "chunked templates"?

### ISSUE THREAD

**Issue by ianmstew** [ianmstew/handlebars-idom#1]
> This may not be the greatest idea, but there are some reasons to do it (for example for chunked rendering on the server) and, since real templates libraries support this, we want to support that.

\- Malte Ubl on [chunked template support in iDOM](https://medium.com/google-developers/introducing-incremental-dom-e98f79ce2c5f#5e85)

Is this a feature we want to support, or should we expect snippets to be fully closed within each parsed template?

Pros to supporting this:
- It's a fundamental feature of iDOM.
- Everyone wants chunked templates :stuck_out_tongue_winking_eye: (mild sarcasm)

Cons
- We cannot use the [HTMLBars parser](https://github.com/tildeio/htmlbars/blob/master/ARCHITECTURE.md#2-convert-to-htmlbars-ast) which will make transpiling to iDOM pretty simple, because its AST is already DOM-aware.
- We will have to use [Handlebars' parser](https://github.com/tildeio/htmlbars/blob/master/ARCHITECTURE.md#1-parse-template-with-vanilla-handlebars), and then process HTML strings manually.  We could accomplish this same as HTMLBars, with https://github.com/tildeio/simple-html-tokenizer.
- What happens when, in a common typo scenario, a developer forgets to close a div?  Could better HTML validation be more favorable than chunking?

Thoughts, @ahumphreys87, @jmeas, @YurkaninRyan, @jridgewell, @MeoMix?

If anyone wants to compare the Handlebars AST to the HTMLBars AST (and the target Babel AST), just clone the project, npm install, open up index.html, then open the console:

![screen shot 2015-09-17 at 12 52 57 am](https://cloud.githubusercontent.com/assets/4119765/9925209/91d8be76-5cd6-11e5-8594-800ac34ba1ba.png)

**Comment by ianmstew** [comment]
I find myself leaning toward supporting a fundamental feature of iDOM and biting the bullet with simple-html-tokenizer.  I don't think it would be that bad, since the tokenizer is doing the hard work and making the tough choices (which elements of the HTML5 spec not to support).

**Comment by YurkaninRyan** [comment]
While it is a fundamental feature of the IDOM, what I took from the article is that the benefit for them adding it was that it makes them a more flexible compilation target.

Do we want to condone chunked templating?  Is that flexibility valuable to our implementation?  I personally find chunking templating pretty messy, and prefer not to write my templates that way.  However, there may be some advantages that I'm missing such as speed or conveniency.

**Comment by ianmstew** [comment]
@YurkaninRyan Great point.  It's a more flexible compilation target, but that doesn't mean our implementation has to be as flexible.  The tradeoff is between smart errors ("no closing tag for <div>") and allowing incomplete DOM manipulation code, which even Malte recognized is a debatable practice.

Corollary thought: We have to become DOM-aware to compile to incremental-dom period; does that make us htmlbars-idom rather than handlebars-idom?  This is especially relevant if we go with htmlbars' AST.

**Comment by jridgewell** [comment]
Personally, I'd say this isn't a practice we should encourage. I've never written a template like that, nor have any of the templates at work (written by others). Especially if it'll be more work...

**Comment by jmeas** [comment]
I'm with @jridgewell . I wouldn't worry about this use case if it's substantially more work. The 99% use case is not doing this : P

**Comment by ianmstew** [comment]
Thanks all for your thoughts.  It wasn't a call I wanted to make without more support.  Going with a DOM-aware AST is going to be way simpler and catch template issues earlier for 99% of use cases, sounds like HTMLBars AST it is.
